### ISSUE TITLE
Uploading subtitles fails in gui

### ISSUE THREAD

**Issue by madebr** [madebr/subdownloader#19]

**Comment by sergiomb2** [comment]
at tag 2.0.19 I could upload subs , but at the ends give me some error , and we resubmit also saw a strange message , but the subs was uploaded, in debug mode ( --debug ) the reply of opensubtitles clearly said that I had upload the sub correctly and on resubmit also clearly says that sub was already submitted . 
Conclusion my guess is that is a problem on handle the replies of opensubtitle.

**Comment by sergiomb2** [comment]
I can confirm this one:

```
[2017-04-12 23:03:43,200] ERROR: subdownloader.SDService.TimeoutFunction # exception in TimeoutFunction.__call__(*args)
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 111, in __call__
    result = self.function(*args)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 624, in _TryUploadSubtitles
    self._token, array, str(int(no_update)))
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1146, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1252, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib64/python3.5/http/client.py", line 975, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
Unhandled exception in thread started by <bound method UploadListModel.ObtainUploadInfo of <subdownloader.client.gui.uploadlistview.UploadListModel object at 0x7f607f455af8>>
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/uploadlistview.py", line 118, in ObtainUploadInfo
    videos, no_update=True)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 583, in TryUploadSubtitles
    return TryUploadSubtitles(videos, no_update)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 111, in __call__
    result = self.function(*args)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 624, in _TryUploadSubtitles
    self._token, array, str(int(no_update)))
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1146, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1252, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib64/python3.5/http/client.py", line 975, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
```


 ```
[2017-04-12 23:06:37,846] ERROR: subdownloader.SDService.TimeoutFunction # exception in TimeoutFunction.__call__(*args)
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 111, in __call__
    result = self.function(*args)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 651, in _UploadSubtitles
    info = self._xmlrpc_server.UploadSubtitles(self._token, movie_info)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1316, in parse_response
    p.feed(data)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 438, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
[2017-04-12 23:06:37,847] DEBUG: subdownloader.callback.ProgressCallback # finish(args=(), kwargs={})

```

**Comment by madebr** [comment]
Some time ago, I revamped subtitle upload. It should work now. Can you verify?

**Comment by sergiomb2** [comment]
funny I have some subtitles to upload for real , I just need verify it first i.e. see the all season :) , so just after end of weekend I can upload it all , but thinking better I can try send just one that I already verified , later tonight . 
best regards

**Comment by madebr** [comment]
Don't be gentle! :smiling_imp:

**Comment by sergiomb2** [comment]
still 
```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/uploadWidget.py", line 217, in on_upload
    success = self.get_state().upload(local_movie)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/state.py", line 179, in upload
    self._OSDBServer.upload_subtitles(local_movie)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 615, in upload_subtitles
    result = self._safe_exec(run_query, None)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 349, in _safe_exec
    result = query()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 614, in run_query
    return self._xmlrpc_server.UploadSubtitles(self._token, query)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1336, in parse_response
    p.feed(data)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 439, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

```

**Comment by madebr** [comment]
Can you try again?
