### ISSUE TITLE
search problem 

### ISSUE THREAD

**Issue by sergiomb2** [madebr/subdownloader#25]
```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchNameWidget.py", line 102, in onButtonSearchByTitle
    movies = s.search_movie(search_text, 'all')
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/FileManagement/search.py", line 83, in search_movie
    search = self.parse_results(xml_page.read())
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/FileManagement/search.py", line 380, in parse_results
    temp_movie = Movie(sub)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/FileManagement/search.py", line 41, in __init__
    self.MovieYear = str(movieInfo['MovieYear'])
KeyError: 'MovieYear'
```

**Comment by madebr** [comment]
What is your query?

**Comment by sergiomb2** [comment]
I don't know , maybe vikings or skins or vikings S04 ...

**Comment by madebr** [comment]
Thanks, Vikings did it

**Comment by madebr** [comment]
Can you test again?

**Comment by sergiomb2** [comment]
search is working, but in search movie by name, the filter for source, have all languages and should just have opensubtitles . 
Search by vikings and filter by portuguese (portugal) crash with : 

Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchNameWidget.py", line 255, in onExpandMovie
    movie.subtitles = temp_movie[0].subtitles
TypeError: 'NoneType' object is not subscriptable
Aborted (core dumped)

**Comment by sergiomb2** [comment]
still got this issue select filter language portuguese , search vikings , first entry on expand and  : 
```
[2017-04-12 23:16:25,733] DEBUG: subdownloader.FileManagement.search # Parsing results from 'http://www.opensubtitles.org/en/search/sublanguageid-all/xml/idmovie-197666' ...
[2017-04-12 23:16:25,738] DEBUG: subdownloader.FileManagement.search # ... FAILED
[2017-04-12 23:16:26,454] DEBUG: subdownloader.FileManagement.search # Parsing results from 'http://www.opensubtitles.org/en/ssearch/sublanguageid-all/xml/idmovie-197666/xml' ...
[2017-04-12 23:16:26,455] DEBUG: subdownloader.FileManagement.search # ... FAILED
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchNameWidget.py", line 267, in onExpandMovie
    movie.subtitles = temp_movie[0].subtitles
TypeError: 'NoneType' object is not subscriptable
```

**Comment by madebr** [comment]
Can you test the master again? Search by name has received a major makeover.

**Comment by madebr** [comment]
Are madebr/subdownloader#25 and madebr/subdownloader#30 still an issue?

**Comment by sergiomb2** [comment]
I'll try check all this evening ...

**Comment by sergiomb2** [comment]
now in the coorect issue,  does not crash but an message popup with "unknown problem occur bla bla" 
the debug:
```
[2017-07-20 01:57:19,974] DEBUG: subdownloader.WebService # ... extraction FAILED (xml error)
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 1374, in extract_subtitle_entries
    nb = int(results_entry.getAttribute('items'))
ValueError: invalid literal for int() with base 10: ''
[2017-07-20 01:57:21,472] DEBUG: subdownloader.callback.ProgressCallback # finish(args=(), kwargs={})
```

**Comment by madebr** [comment]
I pushed a fix related to search  by name.
More specific, I should have fixed a crash when searching for weird queries like 'asdflasjdfklasjdfklaj'.

**Comment by sergiomb2** [comment]
testing the search today with git master

` # Data mismatch: Partial search of subtitles told us movie has 0 subtitles but index told us it has 53 subtitles.`
Enter in loop and never ends ... , but in every loop pop up windows , and if I try minimize the main window of subdownloader and subsownloader pop up the window again every loop, can't write in other place etc , is not a good behavior .

**Comment by madebr** [comment]
Solved in master?

**Comment by sergiomb2** [comment]
I going close this issue , can't reproduce crash anymore , if something new happened , I open a new issue .
