### ISSUE TITLE
just support pymediainfo  >= 1.9 

### ISSUE THREAD

**Issue by sergiomb2** [madebr/subdownloader#26]
I got this error with pymediainfo-2.1.5, but not with pymediainfo-2.1.9
```
Traceback (most recent call last):
  File "./subdownloader.py", line 20, in <module>
    import subdownloader.client.gui
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/__init__.py", line 12, in <module>
    from subdownloader.FileManagement.videofile import VIDEOS_EXT
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/FileManagement/videofile.py", line 8, in <module>
    from subdownloader import metadata
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/metadata.py", line 127, in <module>
    if pymediainfo.MediaInfo.can_parse:
AttributeError: type object 'MediaInfo' has no attribute 'can_parse'

```

**Comment by madebr** [comment]
I know, that method was added by me :)
See https://github.com/madebr/pymediainfo/commit/6b1a2e6f215008b329d6aaae8f0effce4622f7a9
I don't think that is a problem. As long as we document this dependency.
I'll leave this issue open till we have documented it.
I think appropriate places would be README.md and setup.py script.

**Comment by sergiomb2** [comment]
https://github.com/sergiomb2/subdownloader/commit/20d57f634e88a9cbaae1d29edcc4b9371bb1cc38

I can do the setup.py  but just after finish re-modulation , I need a list of list and directories etc etc

**Comment by madebr** [comment]
I have a setup.py in a local branch.
I'm doing some other prep work before pushing it.

**Comment by madebr** [comment]
Fixed with:
madebr/subdownloader@6cbccbc40847a724ed32a68dc78ba830b1e4679c
madebr/subdownloader@24dd534c292673762c558838d74437b8dd0359d1
