### ISSUE TITLE
filter crashes with git master 

### ISSUE THREAD

**Issue by sergiomb2** [madebr/subdownloader#27]
Hi, a quick report of last updates : 
with  Vikings\ Season\ 4\ second\ part\ \(11-20\)\ 720+1080p-ENG_subt/ with filter language PT_pt e PT_br , 

./subdownloader.py 
[2017-04-02 00:42:52,062] WARNING: subdownloader.languages.language # Unknown locale: sr@latin
[2017-04-02 00:42:52,062] WARNING: subdownloader.languages.language # Unknown locale: pt
[2017-04-02 00:42:52,063] WARNING: subdownloader.languages.language # Unknown locale: nn
[2017-04-02 00:42:52,063] WARNING: subdownloader.languages.language # Unknown locale: zza
[2017-04-02 00:42:52,064] WARNING: subdownloader.languages.language # Unknown locale: zh_TW
[2017-04-02 00:42:52,064] WARNING: subdownloader.languages.language # Unknown locale: is
[2017-04-02 00:42:52,064] WARNING: subdownloader.languages.language # Unknown locale: es
[2017-04-02 00:42:52,065] WARNING: subdownloader.languages.language # Unknown locale: ne
[2017-04-02 00:42:52,065] WARNING: subdownloader.languages.language # Unknown locale: ast
[2017-04-02 00:42:52,066] WARNING: subdownloader.languages.language # Unknown locale: af
[2017-04-02 00:42:52,066] WARNING: subdownloader.languages.language # Unknown locale: hi
[2017-04-02 00:42:52,066] WARNING: subdownloader.languages.language # Unknown locale: ta
[2017-04-02 00:42:52,067] WARNING: subdownloader.languages.language # Unknown locale: kn
[2017-04-02 00:42:52,067] WARNING: subdownloader.languages.language # Unknown locale: bn
[2017-04-02 00:42:52,067] WARNING: subdownloader.languages.language # Unknown locale: nb
[2017-04-02 00:42:52,068] WARNING: subdownloader.languages.language # Unknown locale: zh_HK
[2017-04-02 00:42:52,068] WARNING: subdownloader.languages.language # Unknown locale: en_CA
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 341, in onApplyChanges
    self.saveSettings()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 291, in saveSettings
    self.settings.setValue('options/interfaceLang', new_interface_language.locale())
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/languages/language.py", line 52, in locale
    return LANGUAGES[self._id]['locale'][0]
TypeError: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 341, in onApplyChanges
    self.saveSettings()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 291, in saveSettings
    self.settings.setValue('options/interfaceLang', new_interface_language.locale())
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/languages/language.py", line 52, in locale
    return LANGUAGES[self._id]['locale'][0]
TypeError: list indices must be integers or slices, not NoneType
Aborted (core dumped)
sergio@segulix:/home/sergio/fedora-scm/subdownloader/subdownloader.github#./subdownloader.py 
[2017-04-02 00:43:09,612] WARNING: subdownloader.languages.language # Unknown locale: sr@latin
[2017-04-02 00:43:09,612] WARNING: subdownloader.languages.language # Unknown locale: pt
[2017-04-02 00:43:09,612] WARNING: subdownloader.languages.language # Unknown locale: nn
[2017-04-02 00:43:09,613] WARNING: subdownloader.languages.language # Unknown locale: zza
[2017-04-02 00:43:09,613] WARNING: subdownloader.languages.language # Unknown locale: zh_TW
[2017-04-02 00:43:09,613] WARNING: subdownloader.languages.language # Unknown locale: is
[2017-04-02 00:43:09,613] WARNING: subdownloader.languages.language # Unknown locale: es
[2017-04-02 00:43:09,614] WARNING: subdownloader.languages.language # Unknown locale: ne
[2017-04-02 00:43:09,614] WARNING: subdownloader.languages.language # Unknown locale: ast
[2017-04-02 00:43:09,614] WARNING: subdownloader.languages.language # Unknown locale: af
[2017-04-02 00:43:09,614] WARNING: subdownloader.languages.language # Unknown locale: hi
[2017-04-02 00:43:09,615] WARNING: subdownloader.languages.language # Unknown locale: ta
[2017-04-02 00:43:09,615] WARNING: subdownloader.languages.language # Unknown locale: kn
[2017-04-02 00:43:09,615] WARNING: subdownloader.languages.language # Unknown locale: bn
[2017-04-02 00:43:09,615] WARNING: subdownloader.languages.language # Unknown locale: nb
[2017-04-02 00:43:09,615] WARNING: subdownloader.languages.language # Unknown locale: zh_HK
[2017-04-02 00:43:09,616] WARNING: subdownloader.languages.language # Unknown locale: en_CA
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 341, in onApplyChanges
    self.saveSettings()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 291, in saveSettings
    self.settings.setValue('options/interfaceLang', new_interface_language.locale())
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/languages/language.py", line 52, in locale
    return LANGUAGES[self._id]['locale'][0]
TypeError: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 341, in onApplyChanges
    self.saveSettings()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 291, in saveSettings
    self.settings.setValue('options/interfaceLang', new_interface_language.locale())
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/languages/language.py", line 52, in locale
    return LANGUAGES[self._id]['locale'][0]
TypeError: list indices must be integers or slices, not NoneType
Aborted (core dumped)
sergio@segulix:~/fedora-scm/subdownloader/subdownloader.github#./subdownloader.py 
[2017-04-02 00:43:22,273] WARNING: subdownloader.languages.language # Unknown locale: sr@latin
[2017-04-02 00:43:22,273] WARNING: subdownloader.languages.language # Unknown locale: pt
[2017-04-02 00:43:22,274] WARNING: subdownloader.languages.language # Unknown locale: nn
[2017-04-02 00:43:22,274] WARNING: subdownloader.languages.language # Unknown locale: zza
[2017-04-02 00:43:22,274] WARNING: subdownloader.languages.language # Unknown locale: zh_TW
[2017-04-02 00:43:22,275] WARNING: subdownloader.languages.language # Unknown locale: is
[2017-04-02 00:43:22,275] WARNING: subdownloader.languages.language # Unknown locale: es
[2017-04-02 00:43:22,275] WARNING: subdownloader.languages.language # Unknown locale: ne
[2017-04-02 00:43:22,275] WARNING: subdownloader.languages.language # Unknown locale: ast
[2017-04-02 00:43:22,275] WARNING: subdownloader.languages.language # Unknown locale: af
[2017-04-02 00:43:22,276] WARNING: subdownloader.languages.language # Unknown locale: hi
[2017-04-02 00:43:22,276] WARNING: subdownloader.languages.language # Unknown locale: ta
[2017-04-02 00:43:22,276] WARNING: subdownloader.languages.language # Unknown locale: kn
[2017-04-02 00:43:22,276] WARNING: subdownloader.languages.language # Unknown locale: bn
[2017-04-02 00:43:22,276] WARNING: subdownloader.languages.language # Unknown locale: nb
[2017-04-02 00:43:22,277] WARNING: subdownloader.languages.language # Unknown locale: zh_HK
[2017-04-02 00:43:22,277] WARNING: subdownloader.languages.language # Unknown locale: en_CA
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 341, in onApplyChanges
    self.saveSettings()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 291, in saveSettings
    self.settings.setValue('options/interfaceLang', new_interface_language.locale())
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/languages/language.py", line 52, in locale
    return LANGUAGES[self._id]['locale'][0]
TypeError: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchFileWidget.py", line 593, in onButtonDownload
    locale=destinationPath, remote=QFileInfo(destinationPath).fileName()),
KeyError: 'local'
Aborted (core dumped)

**Comment by madebr** [comment]
I fixed the last error but cannot reproduce the first one.
Do you have a reproducer?

**Comment by sergiomb2** [comment]
ah I found the issue it happens when ~/.config/SubDownloader/SubDownloader.conf instead have:
filterSearchLang="por,pob"
interfaceLang=unknown

SubDownloader.conf have   
`    filterSearchLang= `
or   
`    interfaceLang= `

empty attributes and crash on popup menu . 

Before I could crash it with after press download subtitle -> save as when what  download 2 subtitles for same episode 
```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/main.py", line 226, in onMenuPreferences
    dialog = PreferencesDialog(self, state=self._state)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 163, in __init__
    self.readSettings()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/preferences.py", line 229, in readSettings
    self.ui.optionInterfaceLanguage.set_selected_language(self._original_interface_language)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/languageComboBox.py", line 105, in set_selected_language
    index = self._model.language_to_index(lang)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/languageComboBox.py", line 78, in language_to_index
    index = next(index for index, lang in enumerate(self._languages) if language.raw_data() == lang.raw_data())
StopIteration
Aborted (core dumped)
```

in the end it is working very fancy ... 
btw why appears "? pt" (without flag) on  interface language , for Brazilian we have flag and works on the fly ! . 

Thanks and keep your good work 😃

**Comment by sergiomb2** [comment]
```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchFileWidget.py", line 650, in onButtonDownload
    callback=download_callback,
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 1096, in download
    subs = provider_instance.download_subtitles([self])
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 1062, in download_subtitles
    result = self._xmlrpc_server.DownloadSubtitles(self._token, query)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1167, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchFileWidget.py", line 620, in onButtonDownload
    sub.getLanguage().xxx() + suggFileExt
AttributeError: 'OpenSubtitles_SubtitleFile' object has no attribute 'getLanguage'
Aborted (core dumped)
```

can't press save as , for save one second legend for same episode

**Comment by madebr** [comment]
- Setting `interfaceLang` and `interfaceLang` to the empty string does not crash the program for me. I added some robustness (subdownloader/subdownloader@587d213dbb52df9dde55b7d100e1c7fc992a0d00) at the initialization of the interface language combobox in the preferences dialog. So please test whether your reproducer still "works".
- `pt` appeared as an unknown language because I moved the translation files (=`.mo` files) of Portuguese Portuguese from pt_PT to pt. So making Portuguese Portuguese the default Portuguese. (see subdownloader/subdownloader@c49ca82bf204b4823b12ea5318434aff6b696e6e)
I fixed it by adding the locale "pt" as an alternative to "Portuguese (Portugal)". (see subdownloader/subdownloader@e635938f41d6430fdd57376acde28d146bd80705)
- I fixed your download problem (`AttributeError: 'OpenSubtitles_SubtitleFile' object has no attribute 'getLanguage'`) (see subdownloader/subdownloader@4682f2be30fe2dc89a86deb0c57f3344ded29865)

I cannot do this without you testing it in a different environment.

**Comment by sergiomb2** [comment]
looks fixed 😃 I will test better later , have you think in my pull request ? at least you may think in merge some of the commits ...

**Comment by madebr** [comment]
Yeah, but I suggest another way to solve it.
- The version will be bumped when I fix the crash in the name part and have tested/refactored the upload part. The cli part is currently broken. That has to work for a release.
- I will fork pymediainfo in a repo at subdownloader and use pymediainfo as a submodule
  When I create a release, I will create a source archive containing all dependencies (=langdetect, pymediainfo, python-progressbar ...) (except pyqt5)
- You, as a packager, will have to regenerate the _ui.py and mo files yourselve from the downloaded source archive. How exactly, I'll have to check. Maybe through the setup.py file, maybe through a custom script.
- I still have to remove the reference to gui/images/imdb.png

Keep it open, as a reminder to me what a packager needs for a release.

**Comment by madebr** [comment]
Related to the shebang of the main script:
See [PEP394](https://www.python.org/dev/peps/pep-0394/)

SubDownloader works on both Python 2 and 3 so we can safely use python.

**Comment by sergiomb2** [comment]
Aren't we just support python 3 ? I prefer force run it with python3 , if I use #!/usr/bin/env python it use pyhton2 until python3 is not the default, btw we have a big thread about devel mailing list of Fedora ... 
Other answers just this evening   (after work etc )

**Comment by madebr** [comment]
subdownloader/subdownloader#20 was an open question, not a decision.

In the future I would like to seperate SubDownloader into a library and a client part.
i want to support python 2 to keep the potential user base as large as possible.
