### ISSUE TITLE
AttributeError: 'Main' object has no attribute 'SearchVideos' 

### ISSUE THREAD

**Issue by sergiomb2** [madebr/subdownloader#29]
Hello, how are you ? testing today git master with my pull request added , running:

./subdownloader.py -d -V /run/media/sergio/ScanDisk/

```
[2017-07-01 17:44:56,264] DEBUG: subdownloader.modules.metadata # Importing metadata parsing module ...
[2017-07-01 17:44:56,265] DEBUG: subdownloader.modules.metadata # Trying kaa.metadata ...
[2017-07-01 17:44:56,267] DEBUG: subdownloader.modules.metadata # ... Failed!
[2017-07-01 17:44:56,268] DEBUG: subdownloader.modules.metadata # Trying pymediainfo ...
[2017-07-01 17:44:56,269] DEBUG: subdownloader.modules.metadata # ... Failed!
[2017-07-01 17:44:56,270] DEBUG: subdownloader.modules.metadata # parsing module = dummy parser
[2017-07-01 17:44:56,270] DEBUG: subdownloader.modules.metadata # ... Importing metadata parsing module finished
[2017-07-01 17:44:56,801] DEBUG: subdownloader.client.gui # Building main dialog ...
[2017-07-01 17:44:56,837] DEBUG: subdownloader.SDService.SDService # Creating Server with server = None and proxy = None
[2017-07-01 17:44:56,838] DEBUG: subdownloader.client.internationalization # i18n_install( None ) called.
[2017-07-01 17:44:56,839] DEBUG: subdownloader.client.internationalization # locale.getlocale() = (lc="en_US", encoding="UTF-8).
[2017-07-01 17:44:56,839] DEBUG: subdownloader.client.internationalization # i18n_support_locale( locale="en_US" ) called
[2017-07-01 17:44:56,840] DEBUG: subdownloader.client.internationalization # i18n_locale_fallbacks_calculate( locale="en_US" ) called
[2017-07-01 17:44:56,840] DEBUG: subdownloader.client.internationalization # i18n_locale_fallbacks_calculate( lc="en_US" ) = ['en_US', 'en']
[2017-07-01 17:44:56,841] DEBUG: subdownloader.client.internationalization # Locale data in "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/locale/en_US/LC_MESSAGES"?
[2017-07-01 17:44:56,841] DEBUG: subdownloader.client.internationalization # Locale data in "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/locale/en/LC_MESSAGES"?
[2017-07-01 17:44:56,842] DEBUG: subdownloader.client.internationalization # Found! "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/locale/en/LC_MESSAGES" contains subdownloader.mo.
[2017-07-01 17:44:56,842] DEBUG: subdownloader.client.internationalization # i18n_support_locale( lc="en_US" ) = ['en']
[2017-07-01 17:44:56,843] DEBUG: subdownloader.client.internationalization # i18n_install(): installing gettext.translation(domain=subdownloader, localedir=/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/locale, languages=['en'], fallback=True)
[2017-07-01 17:44:57,137] DEBUG: subdownloader.client.gui.searchFileWidget # Current directory: /run/media/sergio/ScanDisk/download
[2017-07-01 17:44:57,219] DEBUG: subdownloader.client.gui.searchNameWidget # Filtering subtitles by language: [<Language:xx=['pt']>]
[2017-07-01 17:44:57,219] DEBUG: subdownloader.client.gui.videotreeview # Clearing VideoTree
Traceback (most recent call last):
  File "./subdownloader.py", line 7, in <module>
    main()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/__main__.py", line 26, in main
    return_code = subdownloader.client.gui.run(options)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/__init__.py", line 38, in run
    main_window = Main(None, "", options)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/main.py", line 67, in __init__
    self.SearchVideos(options.videofile)
AttributeError: 'Main' object has no attribute 'SearchVideos'
```

**Comment by madebr** [comment]
Hey, can you retest?

**Comment by sergiomb2** [comment]
Hello ! , how are you ? yes of course , I wonder what is the state of art ? , can we tag it ? have we many thing to develop yet ? where I may help on coding ? 
Thanks

**Comment by madebr** [comment]
- I recently started reworking the upload tab as that was not working (not finished)
- The cli is not functional, and needs a complete rewrite (but can re-use parts of the gui)
- The gui is currently non-responsive when doing work, that can be fixed in a later version.

**Comment by sergiomb2** [comment]
ok , I tested the new commits , and -V option looks fine, closing this issue . 

Thanks .
