### ISSUE TITLE
Right click on video in file tab causes AttributeError

### ISSUE THREAD

**Issue by madebr** [madebr/subdownloader#30]
Reproducer:

1. Search a folder in the file tab
2. Right click on a video

Stack trace:
```
Traceback (most recent call last):
  File "/home/maarten/programming/subdownloader/subdownloader/client/gui/searchFileWidget.py", line 478, in onContext
    movie_info = video.getMovieInfo()
AttributeError: 'VideoFile' object has no attribute 'getMovieInfo'
```

**Comment by sergiomb2** [comment]
something similar 

```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchFileWidget.py", line 478, in onContext
    movie_info = video.getMovieInfo()
AttributeError: 'VideoFile' object has no attribute 'getMovieInfo'
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/searchFileWidget.py", line 662, in onViewOnlineInfo
    movie_info = video.getMovieInfo()
AttributeError: 'VideoFile' object has no attribute 'getMovieInfo'
Aborted (core dumped)
```

**Comment by madebr** [comment]
Should be fixed by current master.

**Comment by sergiomb2** [comment]
does not crash but an unknown problem occur bla bla 

```
[2017-07-20 01:57:19,974] DEBUG: subdownloader.WebService # ... extraction FAILED (xml error)
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 1374, in extract_subtitle_entries
    nb = int(results_entry.getAttribute('items'))
ValueError: invalid literal for int() with base 10: ''
[2017-07-20 01:57:21,472] DEBUG: subdownloader.callback.ProgressCallback # finish(args=(), kwargs={})
```
